import { Inter, Lexend } from "next/font/google";
import "../globals.css";
import Menu from "../../components/GlobalComponents/Menu";


const inter = Inter({ subsets: ["latin"] });
const lexend = Lexend({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",

});

export const metadata = {
  title: "NextJS x GSAP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.className} bg-black`}>
         <Menu />
        <div className="w-full h-full min-h-screen">{children}</div>
      </body>
    </html>
  );
}
